/*
 * NAMA  : Fiona Avila Putri
 * NIM   : 10119013
 * KELAS : IF1 2019/2020
 */
package kemahasiswaan_10119001_10119013;

/**
 *
 * @author Fiona Avila
 */
public class frm_mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form frm_mahasiswa
     */
    public frm_mahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_jdl_mahasiswa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_key = new javax.swing.JLabel();
        txt_mahasiswa_key = new javax.swing.JTextField();
        lbl_nim = new javax.swing.JLabel();
        lbl_nim1 = new javax.swing.JLabel();
        lbl_nim2 = new javax.swing.JLabel();
        lbl_nim3 = new javax.swing.JLabel();
        lbl_nim4 = new javax.swing.JLabel();
        txt_tmpt_lahir = new javax.swing.JTextField();
        txt_mahasiswa_nama = new javax.swing.JTextField();
        txt_mahasiswa_nim = new javax.swing.JTextField();
        date_tgl_lahir = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_mahasiswa = new javax.swing.JTable();
        btn_mahasiswa_tambah = new javax.swing.JButton();
        btn_mahasiswa_ubah = new javax.swing.JButton();
        btn_mahasiswa_hapus = new javax.swing.JButton();
        btn_mahasiswa_simpan = new javax.swing.JButton();
        btn_mahasiswa_batal = new javax.swing.JButton();
        btn_mahasiswa_keluar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DATA MAHASISWA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(209, 209, 229));

        jPanel2.setBackground(new java.awt.Color(162, 169, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        lbl_jdl_mahasiswa.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        lbl_jdl_mahasiswa.setText("FORM MAHASISWA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(lbl_jdl_mahasiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_jdl_mahasiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(209, 209, 229));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "PENCARIAN DATA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 12))); // NOI18N

        lbl_key.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_key.setText("Masukkan Kata Kunci");

        txt_mahasiswa_key.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_key)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_mahasiswa_key, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_key)
                    .addComponent(txt_mahasiswa_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lbl_nim.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_nim.setText("NIM");

        lbl_nim1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_nim1.setText("Nama");

        lbl_nim2.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_nim2.setText("Tempat Lahir");

        lbl_nim3.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_nim3.setText("Tanggal Lahir");

        lbl_nim4.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_nim4.setText("Alamat");

        txt_tmpt_lahir.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        txt_mahasiswa_nama.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        txt_mahasiswa_nim.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        date_tgl_lahir.setDateFormatString("d MMM yyyy");

        txt_alamat.setColumns(20);
        txt_alamat.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        tbl_mahasiswa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl_mahasiswa.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        tbl_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Tempat Lahir", "Tanggal Lahir", "Alamat"
            }
        ));
        jScrollPane3.setViewportView(tbl_mahasiswa);

        btn_mahasiswa_tambah.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_tambah.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_mahasiswa_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/tambah.png"))); // NOI18N
        btn_mahasiswa_tambah.setText("TAMBAH");
        btn_mahasiswa_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_tambahMouseExited(evt);
            }
        });

        btn_mahasiswa_ubah.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_ubah.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_mahasiswa_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/ubah.png"))); // NOI18N
        btn_mahasiswa_ubah.setText("UBAH");
        btn_mahasiswa_ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_ubahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_ubahMouseExited(evt);
            }
        });

        btn_mahasiswa_hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_hapus.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_mahasiswa_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/hapus.png"))); // NOI18N
        btn_mahasiswa_hapus.setText("HAPUS");
        btn_mahasiswa_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_hapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_hapusMouseExited(evt);
            }
        });

        btn_mahasiswa_simpan.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_simpan.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_mahasiswa_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/simpan.png"))); // NOI18N
        btn_mahasiswa_simpan.setText("SIMPAN");
        btn_mahasiswa_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_simpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_simpanMouseExited(evt);
            }
        });

        btn_mahasiswa_batal.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_batal.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_mahasiswa_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/batal.png"))); // NOI18N
        btn_mahasiswa_batal.setText("BATAL");
        btn_mahasiswa_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_batalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_batalMouseExited(evt);
            }
        });

        btn_mahasiswa_keluar.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_keluar.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_mahasiswa_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/keluar.png"))); // NOI18N
        btn_mahasiswa_keluar.setText("KELUAR");
        btn_mahasiswa_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_keluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mahasiswa_keluarMouseExited(evt);
            }
        });
        btn_mahasiswa_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mahasiswa_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nim2)
                                    .addComponent(lbl_nim)
                                    .addComponent(lbl_nim1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_mahasiswa_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_mahasiswa_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_nim4)
                                            .addComponent(lbl_nim3)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_tmpt_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_mahasiswa_tambah)
                                .addGap(18, 18, 18)
                                .addComponent(btn_mahasiswa_ubah)
                                .addGap(18, 18, 18)
                                .addComponent(btn_mahasiswa_hapus)
                                .addGap(18, 18, 18)
                                .addComponent(btn_mahasiswa_simpan)
                                .addGap(18, 18, 18)
                                .addComponent(btn_mahasiswa_batal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_mahasiswa_keluar))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_nim)
                        .addComponent(lbl_nim3)
                        .addComponent(txt_mahasiswa_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nim1)
                            .addComponent(lbl_nim4)
                            .addComponent(txt_mahasiswa_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nim2)
                            .addComponent(txt_tmpt_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mahasiswa_tambah)
                    .addComponent(btn_mahasiswa_ubah)
                    .addComponent(btn_mahasiswa_hapus)
                    .addComponent(btn_mahasiswa_simpan)
                    .addComponent(btn_mahasiswa_batal)
                    .addComponent(btn_mahasiswa_keluar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(956, 684));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frm_utama u = new frm_utama();
        u.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_mahasiswa_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mahasiswa_keluarActionPerformed
        frm_utama u = new frm_utama();
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_mahasiswa_keluarActionPerformed

    private void btn_mahasiswa_tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_tambahMouseEntered
        //[162,169,226]
        btn_mahasiswa_tambah.setBackground(new java.awt.Color(128,136,203));
        btn_mahasiswa_tambah.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_mahasiswa_tambahMouseEntered

    private void btn_mahasiswa_tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_tambahMouseExited
        btn_mahasiswa_tambah.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_tambah.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_mahasiswa_tambahMouseExited

    private void btn_mahasiswa_ubahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_ubahMouseEntered
        btn_mahasiswa_ubah.setBackground(new java.awt.Color(128,136,203));
        btn_mahasiswa_ubah.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_mahasiswa_ubahMouseEntered

    private void btn_mahasiswa_ubahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_ubahMouseExited
        btn_mahasiswa_ubah.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_ubah.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_mahasiswa_ubahMouseExited

    private void btn_mahasiswa_hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_hapusMouseEntered
        btn_mahasiswa_hapus.setBackground(new java.awt.Color(128,136,203));
        btn_mahasiswa_hapus.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_mahasiswa_hapusMouseEntered

    private void btn_mahasiswa_hapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_hapusMouseExited
        btn_mahasiswa_hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_hapus.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_mahasiswa_hapusMouseExited

    private void btn_mahasiswa_simpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_simpanMouseEntered
        btn_mahasiswa_simpan.setBackground(new java.awt.Color(128,136,203));
        btn_mahasiswa_simpan.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_mahasiswa_simpanMouseEntered

    private void btn_mahasiswa_simpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_simpanMouseExited
        btn_mahasiswa_simpan.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_simpan.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_mahasiswa_simpanMouseExited

    private void btn_mahasiswa_batalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_batalMouseEntered
        btn_mahasiswa_batal.setBackground(new java.awt.Color(128,136,203));
        btn_mahasiswa_batal.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_mahasiswa_batalMouseEntered

    private void btn_mahasiswa_batalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_batalMouseExited
        btn_mahasiswa_batal.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_batal.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_mahasiswa_batalMouseExited

    private void btn_mahasiswa_keluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_keluarMouseEntered
        //[255,0,0]
        btn_mahasiswa_keluar.setBackground(new java.awt.Color(255,102,102));
        btn_mahasiswa_keluar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_mahasiswa_keluarMouseEntered

    private void btn_mahasiswa_keluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mahasiswa_keluarMouseExited
        btn_mahasiswa_keluar.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa_keluar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_mahasiswa_keluarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mahasiswa_batal;
    private javax.swing.JButton btn_mahasiswa_hapus;
    private javax.swing.JButton btn_mahasiswa_keluar;
    private javax.swing.JButton btn_mahasiswa_simpan;
    private javax.swing.JButton btn_mahasiswa_tambah;
    private javax.swing.JButton btn_mahasiswa_ubah;
    private com.toedter.calendar.JDateChooser date_tgl_lahir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_jdl_mahasiswa;
    private javax.swing.JLabel lbl_key;
    private javax.swing.JLabel lbl_nim;
    private javax.swing.JLabel lbl_nim1;
    private javax.swing.JLabel lbl_nim2;
    private javax.swing.JLabel lbl_nim3;
    private javax.swing.JLabel lbl_nim4;
    private javax.swing.JTable tbl_mahasiswa;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_mahasiswa_key;
    private javax.swing.JTextField txt_mahasiswa_nama;
    private javax.swing.JTextField txt_mahasiswa_nim;
    private javax.swing.JTextField txt_tmpt_lahir;
    // End of variables declaration//GEN-END:variables
}
