/*
 * NAMA  : Fiona Avila Putri
 * NIM   : 10119013
 * KELAS : IF1 2019/2020
 */
package kemahasiswaan_10119001_10119013;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Fiona Avila
 */
public class frm_konf_bayar extends javax.swing.JFrame {

    /**
     * Creates new form frm_konf_bayar
     */
    
    koneksi dbsetting;
    String driver, database, user, pass;
    int point;
    
    public frm_konf_bayar() {
        initComponents();
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        
    }

    public void tambah_point_member(){
        frm_kasus k = new frm_kasus();
        try{
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String sql = "UPDATE t_member "
                    + "SET Point = '"+txt_total_point_konf.getText()+"' "
                    + "WHERE IdMember = '"+txt_id_member_konf.getText()+"';";
            stt.executeUpdate(sql);
            stt.close();
            kon.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Gagal Membayar!", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_total_bayar_konf1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_no_struk_konf = new javax.swing.JLabel();
        txt_no_struk_konf = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_total_bayar_konf2 = new javax.swing.JLabel();
        txt_total_bayar_konf = new javax.swing.JTextField();
        lbl_uang_bayar_konf = new javax.swing.JLabel();
        txt_uang_bayar_konf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_uang_bayar_konf1 = new javax.swing.JLabel();
        txt_uang_kembalian_konf = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbl_tambah_point_konf = new javax.swing.JLabel();
        txt_tambah_point_konf = new javax.swing.JTextField();
        lbl_point_konf = new javax.swing.JLabel();
        txt_point_konf = new javax.swing.JTextField();
        lbl_total_point_konf = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_total_point_konf = new javax.swing.JTextField();
        lbl_id_member_konf = new javax.swing.JLabel();
        txt_id_member_konf = new javax.swing.JTextField();
        lbl_nama_member_konf = new javax.swing.JLabel();
        txt_nama_member_konf = new javax.swing.JTextField();
        btn_simpan_konf = new javax.swing.JButton();
        btn_batal_konf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KONFIRMASI PEMBAYARAN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(209, 209, 229));

        lbl_total_bayar_konf1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(209, 209, 229));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Struk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 12))); // NOI18N

        lbl_no_struk_konf.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbl_no_struk_konf.setText("NO STRUK");

        txt_no_struk_konf.setEditable(false);
        txt_no_struk_konf.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_no_struk_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_struk_konfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_no_struk_konf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_no_struk_konf, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_no_struk_konf)
                    .addComponent(txt_no_struk_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(209, 209, 229));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pembayaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 12))); // NOI18N

        lbl_total_bayar_konf2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbl_total_bayar_konf2.setText("TOTAL BAYAR");

        txt_total_bayar_konf.setEditable(false);
        txt_total_bayar_konf.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_total_bayar_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_bayar_konfActionPerformed(evt);
            }
        });

        lbl_uang_bayar_konf.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbl_uang_bayar_konf.setText("UANG BAYAR");

        txt_uang_bayar_konf.setEditable(false);
        txt_uang_bayar_konf.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_uang_bayar_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uang_bayar_konfActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        lbl_uang_bayar_konf1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbl_uang_bayar_konf1.setText("UANG KEMBALIAN");

        txt_uang_kembalian_konf.setEditable(false);
        txt_uang_kembalian_konf.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_uang_kembalian_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uang_kembalian_konfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_total_bayar_konf2)
                            .addComponent(lbl_uang_bayar_konf))
                        .addGap(18, 37, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_uang_bayar_konf, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addComponent(txt_total_bayar_konf)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_uang_bayar_konf1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_uang_kembalian_konf)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total_bayar_konf2)
                    .addComponent(txt_total_bayar_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_uang_bayar_konf)
                    .addComponent(txt_uang_bayar_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_uang_bayar_konf1)
                    .addComponent(txt_uang_kembalian_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(209, 209, 229));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Member", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 12))); // NOI18N

        lbl_tambah_point_konf.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbl_tambah_point_konf.setText("Tambah Point");

        txt_tambah_point_konf.setEditable(false);
        txt_tambah_point_konf.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_tambah_point_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tambah_point_konfActionPerformed(evt);
            }
        });

        lbl_point_konf.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbl_point_konf.setText("Point Awal");

        txt_point_konf.setEditable(false);
        txt_point_konf.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_point_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_point_konfActionPerformed(evt);
            }
        });

        lbl_total_point_konf.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbl_total_point_konf.setText("Total Point");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        txt_total_point_konf.setEditable(false);
        txt_total_point_konf.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_total_point_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_point_konfActionPerformed(evt);
            }
        });

        lbl_id_member_konf.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbl_id_member_konf.setText("Id Member");

        txt_id_member_konf.setEditable(false);
        txt_id_member_konf.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_id_member_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_member_konfActionPerformed(evt);
            }
        });

        lbl_nama_member_konf.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbl_nama_member_konf.setText("Nama Member");

        txt_nama_member_konf.setEditable(false);
        txt_nama_member_konf.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_nama_member_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_member_konfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_point_konf)
                            .addComponent(lbl_tambah_point_konf))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tambah_point_konf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_point_konf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_total_point_konf)
                        .addGap(36, 36, 36)
                        .addComponent(txt_total_point_konf, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_id_member_konf)
                        .addGap(34, 34, 34)
                        .addComponent(txt_id_member_konf))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_nama_member_konf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nama_member_konf)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_point_konf)
                    .addComponent(txt_point_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id_member_konf)
                    .addComponent(txt_id_member_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tambah_point_konf)
                    .addComponent(txt_tambah_point_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nama_member_konf)
                    .addComponent(txt_nama_member_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total_point_konf)
                    .addComponent(txt_total_point_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_simpan_konf.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_simpan_konf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/simpan.png"))); // NOI18N
        btn_simpan_konf.setText("Simpan");
        btn_simpan_konf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_simpan_konfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_simpan_konfMouseExited(evt);
            }
        });
        btn_simpan_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_konfActionPerformed(evt);
            }
        });

        btn_batal_konf.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_batal_konf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/batal.png"))); // NOI18N
        btn_batal_konf.setText("Batal");
        btn_batal_konf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_batal_konfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_batal_konfMouseExited(evt);
            }
        });
        btn_batal_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_konfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_total_bayar_konf1))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_simpan_konf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal_konf)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lbl_total_bayar_konf1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan_konf)
                    .addComponent(btn_batal_konf))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(602, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_total_bayar_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_bayar_konfActionPerformed
        
    }//GEN-LAST:event_txt_total_bayar_konfActionPerformed

    private void txt_uang_bayar_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uang_bayar_konfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uang_bayar_konfActionPerformed

    private void txt_uang_kembalian_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uang_kembalian_konfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uang_kembalian_konfActionPerformed

    private void txt_tambah_point_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tambah_point_konfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tambah_point_konfActionPerformed

    private void txt_no_struk_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_struk_konfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_struk_konfActionPerformed

    private void btn_simpan_konfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpan_konfMouseEntered
        btn_simpan_konf.setBackground(new java.awt.Color(128,136,203));
        btn_simpan_konf.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_simpan_konfMouseEntered

    private void btn_batal_konfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batal_konfMouseEntered
        btn_batal_konf.setBackground(new java.awt.Color(128,136,203));
        btn_batal_konf.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_batal_konfMouseEntered

    private void btn_simpan_konfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpan_konfMouseExited
        btn_simpan_konf.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpan_konf.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_simpan_konfMouseExited

    private void btn_batal_konfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batal_konfMouseExited
        btn_batal_konf.setBackground(new java.awt.Color(255, 255, 255));
        btn_batal_konf.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_batal_konfMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void btn_simpan_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_konfActionPerformed
        try{
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String sql = "UPDATE t_struk "
                    + "SET WaktuStruk = now(), "
                    + "TotalBayar = '"+txt_total_bayar_konf.getText()+"' "
                    + "WHERE NoStruk = '"+txt_no_struk_konf.getText()+"';";
            stt.executeUpdate(sql);
            stt.close();
            kon.close();
            tambah_point_member();
            frm_kasus k = new frm_kasus();
            k.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Gagal Membayar!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_simpan_konfActionPerformed

    private void btn_batal_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_konfActionPerformed
        hide();
        frm_kasus k = new frm_kasus();
        k.setVisible(true);
    }//GEN-LAST:event_btn_batal_konfActionPerformed

    private void txt_point_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_point_konfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_point_konfActionPerformed

    private void txt_total_point_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_point_konfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_point_konfActionPerformed

    private void txt_id_member_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_member_konfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_member_konfActionPerformed

    private void txt_nama_member_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_member_konfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_member_konfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_konf_bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_konf_bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_konf_bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_konf_bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_konf_bayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal_konf;
    private javax.swing.JButton btn_simpan_konf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_id_member_konf;
    private javax.swing.JLabel lbl_nama_member_konf;
    private javax.swing.JLabel lbl_no_struk_konf;
    private javax.swing.JLabel lbl_point_konf;
    private javax.swing.JLabel lbl_tambah_point_konf;
    private javax.swing.JLabel lbl_total_bayar_konf1;
    private javax.swing.JLabel lbl_total_bayar_konf2;
    private javax.swing.JLabel lbl_total_point_konf;
    private javax.swing.JLabel lbl_uang_bayar_konf;
    private javax.swing.JLabel lbl_uang_bayar_konf1;
    public javax.swing.JTextField txt_id_member_konf;
    public javax.swing.JTextField txt_nama_member_konf;
    public javax.swing.JTextField txt_no_struk_konf;
    public javax.swing.JTextField txt_point_konf;
    public javax.swing.JTextField txt_tambah_point_konf;
    public javax.swing.JTextField txt_total_bayar_konf;
    public javax.swing.JTextField txt_total_point_konf;
    public javax.swing.JTextField txt_uang_bayar_konf;
    public javax.swing.JTextField txt_uang_kembalian_konf;
    // End of variables declaration//GEN-END:variables
}
