/*
 * NAMA  : Fiona Avila Putri
 * NIM   : 10119013
 * KELAS : IF1 2019/2020
 */
package kemahasiswaan_10119001_10119013;

/**
 *
 * @author Fiona Avila
 */
public class frm_utama extends javax.swing.JFrame {

    /**
     * Creates new form frm_utama
     */
    public frm_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_judul = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_data_mahasiswa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_mata_kuliah = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_nilai = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_nilai_akhir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_kasus = new javax.swing.JButton();
        img_10119001 = new javax.swing.JLabel();
        img_10119013 = new javax.swing.JLabel();
        nim_10119001 = new javax.swing.JLabel();
        nim_10119013 = new javax.swing.JLabel();
        nama_10119001 = new javax.swing.JLabel();
        nama_10119013 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI KEMAHASISWAAN");

        jPanel1.setBackground(new java.awt.Color(209, 209, 229));

        lbl_judul.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        lbl_judul.setText("APLIKASI KEMAHASISWAAN");
        lbl_judul.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));

        jToolBar1.setBackground(new java.awt.Color(162, 169, 226));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        jToolBar1.setRollover(true);

        btn_data_mahasiswa.setBackground(new java.awt.Color(162, 169, 226));
        btn_data_mahasiswa.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_data_mahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/mahasiswa.png"))); // NOI18N
        btn_data_mahasiswa.setText("Data Mahasiswa");
        btn_data_mahasiswa.setBorderPainted(false);
        btn_data_mahasiswa.setFocusable(false);
        btn_data_mahasiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_data_mahasiswa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_data_mahasiswa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_data_mahasiswaFocusGained(evt);
            }
        });
        btn_data_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_data_mahasiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_data_mahasiswaMouseExited(evt);
            }
        });
        btn_data_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_mahasiswaActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_data_mahasiswa);
        jToolBar1.add(jSeparator1);

        btn_mata_kuliah.setBackground(new java.awt.Color(162, 169, 226));
        btn_mata_kuliah.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_mata_kuliah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/mata_kuliah.png"))); // NOI18N
        btn_mata_kuliah.setText("Data Mata Kuliah");
        btn_mata_kuliah.setBorderPainted(false);
        btn_mata_kuliah.setFocusable(false);
        btn_mata_kuliah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mata_kuliah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mata_kuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mata_kuliahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mata_kuliahMouseExited(evt);
            }
        });
        btn_mata_kuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mata_kuliahActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mata_kuliah);
        jToolBar1.add(jSeparator2);

        btn_nilai.setBackground(new java.awt.Color(162, 169, 226));
        btn_nilai.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_nilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/nilai.png"))); // NOI18N
        btn_nilai.setText("Data Nilai");
        btn_nilai.setBorderPainted(false);
        btn_nilai.setFocusable(false);
        btn_nilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nilai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nilaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_nilaiMouseExited(evt);
            }
        });
        btn_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilaiActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nilai);
        jToolBar1.add(jSeparator3);

        btn_nilai_akhir.setBackground(new java.awt.Color(162, 169, 226));
        btn_nilai_akhir.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_nilai_akhir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/nilai_akhir.png"))); // NOI18N
        btn_nilai_akhir.setText("Simulasi Nilai Akhir");
        btn_nilai_akhir.setBorderPainted(false);
        btn_nilai_akhir.setFocusable(false);
        btn_nilai_akhir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nilai_akhir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nilai_akhir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nilai_akhirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_nilai_akhirMouseExited(evt);
            }
        });
        btn_nilai_akhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilai_akhirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nilai_akhir);
        jToolBar1.add(jSeparator4);

        btn_kasus.setBackground(new java.awt.Color(162, 169, 226));
        btn_kasus.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btn_kasus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/kasus.png"))); // NOI18N
        btn_kasus.setText("Simulasi Kasus");
        btn_kasus.setBorderPainted(false);
        btn_kasus.setFocusable(false);
        btn_kasus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_kasus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_kasus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_kasusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_kasusMouseExited(evt);
            }
        });
        btn_kasus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kasusActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_kasus);

        img_10119001.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/10119001.png"))); // NOI18N
        img_10119001.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        img_10119001.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_10119001MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_10119001MouseExited(evt);
            }
        });

        img_10119013.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10119001_10119013/10119013.png"))); // NOI18N
        img_10119013.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        img_10119013.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_10119013MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_10119013MouseExited(evt);
            }
        });

        nim_10119001.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        nim_10119001.setText("10119001");
        nim_10119001.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nim_10119001MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nim_10119001MouseExited(evt);
            }
        });

        nim_10119013.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        nim_10119013.setText("10119013");
        nim_10119013.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nim_10119013MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nim_10119013MouseExited(evt);
            }
        });

        nama_10119001.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        nama_10119001.setText("ARSY OPRAZA AKMA");
        nama_10119001.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nama_10119001MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nama_10119001MouseExited(evt);
            }
        });

        nama_10119013.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        nama_10119013.setText("FIONA AVILA PUTRI");
        nama_10119013.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nama_10119013MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nama_10119013MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(img_10119001)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img_10119013)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(nim_10119001)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nim_10119013)
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(nama_10119001)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nama_10119013)
                .addGap(74, 74, 74))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(img_10119013)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_judul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(img_10119001)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nim_10119001)
                    .addComponent(nim_10119013))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_10119001)
                    .addComponent(nama_10119013))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu1MouseExited(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jMenuItem1.setText("Tentang Pembuat");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseExited(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(618, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_data_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_mahasiswaActionPerformed
        frm_mahasiswa mhs = new frm_mahasiswa();
        mhs.setVisible(true);
        hide();
    }//GEN-LAST:event_btn_data_mahasiswaActionPerformed

    private void btn_mata_kuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mata_kuliahActionPerformed
        frm_mata_kuliah mk = new frm_mata_kuliah();
        mk.setVisible(true);
        hide();
    }//GEN-LAST:event_btn_mata_kuliahActionPerformed

    private void btn_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nilaiActionPerformed
        frm_nilai n = new frm_nilai();
        n.setVisible(true);
        hide();
    }//GEN-LAST:event_btn_nilaiActionPerformed

    private void btn_nilai_akhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nilai_akhirActionPerformed
        frm_nilai_akhir na = new frm_nilai_akhir();
        na.setVisible(true);
        hide();
    }//GEN-LAST:event_btn_nilai_akhirActionPerformed

    private void btn_kasusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kasusActionPerformed
        frm_kasus k = new frm_kasus();
        k.setVisible(true);
        hide();
    }//GEN-LAST:event_btn_kasusActionPerformed

    private void btn_data_mahasiswaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_data_mahasiswaFocusGained
        
    }//GEN-LAST:event_btn_data_mahasiswaFocusGained

    private void btn_data_mahasiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_data_mahasiswaMouseEntered
        btn_data_mahasiswa.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_data_mahasiswaMouseEntered

    private void btn_data_mahasiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_data_mahasiswaMouseExited
        btn_data_mahasiswa.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_data_mahasiswaMouseExited

    private void btn_mata_kuliahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mata_kuliahMouseEntered
        btn_mata_kuliah.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_mata_kuliahMouseEntered

    private void btn_mata_kuliahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mata_kuliahMouseExited
        btn_mata_kuliah.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_mata_kuliahMouseExited

    private void btn_nilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nilaiMouseEntered
        btn_nilai.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_nilaiMouseEntered

    private void btn_nilaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nilaiMouseExited
        btn_nilai.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_nilaiMouseExited

    private void btn_nilai_akhirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nilai_akhirMouseEntered
        btn_nilai_akhir.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_nilai_akhirMouseEntered

    private void btn_nilai_akhirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nilai_akhirMouseExited
        btn_nilai_akhir.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_nilai_akhirMouseExited

    private void btn_kasusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kasusMouseEntered
        btn_kasus.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn_kasusMouseEntered

    private void btn_kasusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kasusMouseExited
        btn_kasus.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btn_kasusMouseExited

    private void img_10119001MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_10119001MouseEntered
        nim_10119001.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
        nama_10119001.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
    }//GEN-LAST:event_img_10119001MouseEntered

    private void img_10119001MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_10119001MouseExited
        nim_10119001.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
        nama_10119001.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
    }//GEN-LAST:event_img_10119001MouseExited

    private void img_10119013MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_10119013MouseEntered
        nim_10119013.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
        nama_10119013.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
    }//GEN-LAST:event_img_10119013MouseEntered

    private void img_10119013MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_10119013MouseExited
        nim_10119013.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
        nama_10119013.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
    }//GEN-LAST:event_img_10119013MouseExited

    private void nim_10119001MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nim_10119001MouseEntered
        nim_10119001.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
    }//GEN-LAST:event_nim_10119001MouseEntered

    private void nim_10119001MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nim_10119001MouseExited
        nim_10119001.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
    }//GEN-LAST:event_nim_10119001MouseExited

    private void nama_10119001MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nama_10119001MouseEntered
        nama_10119001.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
    }//GEN-LAST:event_nama_10119001MouseEntered

    private void nama_10119001MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nama_10119001MouseExited
        nama_10119001.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
    }//GEN-LAST:event_nama_10119001MouseExited

    private void nim_10119013MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nim_10119013MouseEntered
        nim_10119013.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
    }//GEN-LAST:event_nim_10119013MouseEntered

    private void nim_10119013MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nim_10119013MouseExited
        nim_10119013.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
    }//GEN-LAST:event_nim_10119013MouseExited

    private void nama_10119013MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nama_10119013MouseEntered
        nama_10119013.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
    }//GEN-LAST:event_nama_10119013MouseEntered

    private void nama_10119013MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nama_10119013MouseExited
        nama_10119013.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
    }//GEN-LAST:event_nama_10119013MouseExited

    private void jMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseEntered
       jMenu1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
    }//GEN-LAST:event_jMenu1MouseEntered

    private void jMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseExited
        jMenu1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
    }//GEN-LAST:event_jMenu1MouseExited

    private void jMenuItem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseEntered
        jMenuItem1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12));
    }//GEN-LAST:event_jMenuItem1MouseEntered

    private void jMenuItem1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseExited
        jMenuItem1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12));
    }//GEN-LAST:event_jMenuItem1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_data_mahasiswa;
    private javax.swing.JButton btn_kasus;
    private javax.swing.JButton btn_mata_kuliah;
    private javax.swing.JButton btn_nilai;
    private javax.swing.JButton btn_nilai_akhir;
    private javax.swing.JLabel img_10119001;
    private javax.swing.JLabel img_10119013;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel nama_10119001;
    private javax.swing.JLabel nama_10119013;
    private javax.swing.JLabel nim_10119001;
    private javax.swing.JLabel nim_10119013;
    // End of variables declaration//GEN-END:variables
}
